<?php
$title = 'Ajout d\'un article';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('articles', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('articles_id'));
echo $this->formRow($form->get('articles_nom'));
echo $this->formRow($form->get('articles_ref'));
echo $this->formRow($form->get('articles_stock'));
echo $this->formRow($form->get('articles_min'));
echo $this->formRow($form->get('articles_prix'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
