<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Clients\module'                       => __DIR__ . '/Module.php',
  'Clients\Controller\ClientsController' => __DIR__ . '/src/Clients/Controller/ClientsController.php',
  'Clients\Form\FormulaireComplexe'      => __DIR__ . '/src/Clients/Form/FormulaireComplexe.php',
  'Clients\Form\FormulaireFichier'       => __DIR__ . '/src/Clients/Form/FormulaireFichier.php',
  'Clients\Model\Clients'                => __DIR__ . '/src/Clients/Model/Clients.php',
);
